### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Sakartu** [eriktews/gensafeprime#4]
I have implemented a python3 version of gensafeprime at https://github.com/Sakartu/gensafeprime, but am unsure what the procedures are to get this into pypi or create a version that works in both python versions.

**Comment by eriktews** [comment]
Hi, that looks good.

So have a look here: https://docs.python.org/2/howto/cporting.html

#if PY_MAJOR_VERSION >= 3
#define IS_PY3K
#endif

You may look at PY_MAJOR_VERSION in a compiler macro, and depending on the value, you use different calls. I think you should be able to make your version compatible with python 2 and 3 easily. When this looks good, I can merge that.

**Comment by Sakartu** [comment]
Done, both versions compile (with warnings) and properly generate primes on my Mac, changes can be found in https://github.com/Sakartu/gensafeprime/commit/9cf3a3065f8d6c5e6f576d687edbdbae4321cbe5

**Comment by eriktews** [comment]
Thanks, everything compiles without warning on my Debian system. This has been added in v1.5 with commit 31dc49788f3f37adb0b3ee5c1607d9d1ca3c4ef9.
